name: anaconda-linter
channels:
  - defaults

dependencies:
  - python
  # build
  - setuptools
  - pip
  # run
  - percy ==0.0.5
  - ruamel.yaml
  - license-expression
  - jinja2
  - conda-build
  - jsonschema
  - networkx
  - requests
  # test
  - make
  - pytest
  - pre-commit
  # plug ins
  - pytest-cov
  - pytest-html
