name: anaconda-linter

dependencies:
  - python
  # build
  - setuptools
  - pip
  # run
  - ruamel.yaml
  - license-expression
  - jinja2
  - conda-build
  - jsonschema
  - networkx
  - requests
  # test
  - make
  - pytest
  - pre-commit
  # plug ins
  - pytest-cov
  - pytest-html
