name: Set up environment
description: Set up an anaconda-linter environment

runs:
  using: "composite"
  steps:
    - name: Cache conda env
      id: cache-conda
      uses: actions/cache@v3.3.2
      env:
        cache-name: conda-env-cache
      with:
        path: '/usr/share/miniconda/envs'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Create Environment
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      run: |
        conda update -n base -c defaults conda
        source $CONDA/etc/profile.d/conda.sh
        conda init bash
        conda env create -f environment.yaml --name anaconda-linter --force
        conda run --name anaconda-linter pip install .
        conda activate anaconda-linter
      shell: bash
