name: Set up environment
description: Set up an anaconda-linter environment
on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - name: Cache conda env
      id: cache-conda
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      env:
        cache-name: conda-env-cache
      with:
        path: '/usr/share/miniconda/envs'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Create Environment
      if: ${{ steps.cache-conda.outputs.cache-hit == false }}
      run: |
        source $CONDA/bin/activate
        make environment
      shell: bash
