on:
  push:
    branches:
      - main
    tags:
      - v*

name: Build Conda Package

jobs:
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
          with:
            python-version: '3.9'
        - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # tag=v3.0.0
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - name: Create Environment
        run: |
          source $CONDA/bin/activate
          conda activate base
          conda install --yes --quiet conda-build anaconda-client
      - name: Build Conda Package
        run: |
          source $CONDA/bin/activate
          conda activate base
          conda build recipe --croot ./pkgs -c conda-forge
      - name: Upload Package
        env:
          ANACONDA_ORG_TOKEN: ${{ secrets.ANACONDA_ORG_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          source $CONDA/bin/activate
          conda activate base
          anaconda --token ${ANACONDA_ORG_TOKEN} upload \
            --force --no-progress \
            --user distro-tooling \
            ./pkgs/**/*.tar.bz2
      - name: Archive CI Artefacts
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        if: ${{ always() }}
        with:
          name: build-artifacts
          path: pkgs/**
          retention-days: 5
