on:
  push:
    branches:
      - main
  pull_request:


name: Test

jobs:
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4
          with:
            python-version: '3.9'
        - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # tag=v3.0.0
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Cache conda env
        id: cache-conda
        uses: actions/cache@1c73980b09e7aea7201f325a7aa3ad00beddcdda # tag=v3
        env:
          cache-name: conda-env-cache
        with:
          path: '/usr/share/miniconda/envs'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Create Environment
        if: ${{ steps.cache-conda.outputs.cache-hit == false }}
        run: |
          source $CONDA/bin/activate
          make environment
      - name: Run tests
        run: |
          source $CONDA/bin/activate
          conda activate anaconda-linter
          make test
      - name: Archive CI Artefacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: ci-artifacts
          path: artifacts/**
          retention-days: 5
