on:
  push:
    branches:
      - main
  pull_request:


name: Test

jobs:
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4
          with:
            python-version: '3.9'
        - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # tag=v3.0.0
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Cache conda env
        id: cache-conda
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        env:
          cache-name: conda-env-cache
        with:
          path: '/usr/share/miniconda/envs'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Create Environment
        if: ${{ steps.cache-conda.outputs.cache-hit == false }}
        run: |
          source $CONDA/bin/activate
          make environment
      - name: Run tests
        run: |
          source $CONDA/bin/activate
          conda activate anaconda-linter
          make test
      - name: Archive CI Artefacts
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: ci-artifacts
          path: artifacts/**
          retention-days: 5
  build-recipe:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
        - name: Cache conda env
          id: cache-conda
          uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
          env:
            cache-name: conda-env-cache
          with:
            path: '/usr/share/miniconda/envs'
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Build package
          run: |
            source $CONDA/bin/activate
            conda install conda-build
            conda-build .
  lint-recipe:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
        - name: Cache conda env
          id: cache-conda
          uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
          env:
            cache-name: conda-env-cache
          with:
            path: '/usr/share/miniconda/envs'
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Create Environment
          if: ${{ steps.cache-conda.outputs.cache-hit == false }}
          run: |
            source $CONDA/bin/activate
            make environment
        - name: Run lint
          run: |
            source $CONDA/bin/activate
            conda activate anaconda-linter
            OUTPUT=`conda-lint .`
            [[ ${OUTPUT} == "All checks OK" ]] || exit 1
