on:
  push:
    branches:
      - main
  pull_request:


name: Test

jobs:
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: ./.github/actions/setup-env
        - uses: pre-commit/action@v3.0.0
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-env
      - name: Run tests
        run: |
          make test
      - name: Archive CI Artefacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ci-artifacts
          path: artifacts/**
          retention-days: 5
  build-recipe:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.1
        - name: Cache conda env
          id: cache-conda
          uses: actions/cache@v3.3.2
          env:
            cache-name: conda-env-cache
          with:
            path: '/usr/share/miniconda/envs'
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Build package
          run: |
            source $CONDA/bin/activate
            conda install conda-build
            conda-build .
  lint-recipe:
      runs-on: ubuntu-latest
      steps:
        - uses: ./.github/actions/setup-env
        - name: Run lint
          run: |
            OUTPUT=`conda-lint .`
            [[ ${OUTPUT} == "All checks OK" ]] || exit 1
