on:
  push:
    branches:
      - main
  pull_request:


name: Test

jobs:
  pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        - uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9 # v4
          with:
            python-version: '3.9'
        - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # tag=v3.0.0
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      - name: Cache conda env
        id: cache-conda
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        env:
          cache-name: conda-env-cache
        with:
          path: '/usr/share/miniconda/envs'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Create Environment
        if: ${{ steps.cache-conda.outputs.cache-hit == false }}
        run: |
          source $CONDA/bin/activate
          make environment
      - name: Run tests
        run: |
          source $CONDA/bin/activate
          conda activate anaconda-linter
          make test
      - name: Archive CI Artefacts
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: ci-artifacts
          path: artifacts/**
          retention-days: 5
