on:
  schedule:
    - cron: '0 0 1 1-12 *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Update License Files
jobs:
  update_licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: '3.10'
      - name: Install Requests
        run: pip install requests
      - name: Run Script
        run: python scripts/update_licenses.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6
        with:
          title: Update Licenses and Exceptions
          branch-suffix: random
          draft: false
          add-paths: 'anaconda_linter/data/*.txt'
