on:
  schedule:
    - cron: '0 0 1 1-12 *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Update License Files
jobs:
  update_licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Setup Python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4
        with:
          python-version: '3.10'
      - name: Install Requests
        run: pip install requests
      - name: Run Script
        run: python scripts/update_licenses.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5b4a9f6a9e2af26e5f02351490b90d01eb8ec1e5 # v5
        with:
          title: Update Licenses and Exceptions
          branch-suffix: random
          draft: false
          add-paths: 'anaconda_linter/data/*.txt'
